### ISSUE TITLE
Would you accept a pull request adding HTTP-01 authentication?

### ISSUE THREAD

**Issue by saitho** [terraform-providers/terraform-provider-acme#108]
Hi there,

I am aware that `acme_certificate` only supports DNS-01 as Terraform is expected not to run on the server that uses the certificate. However I'm using Terraform to manage resources on my server (containers, configuration files, etc) - so I am running it on the server that uses the certificate and would like to use the Cloud Provider-independent HTTP-01 authentication.

I've prepared a rudimentary implementation on that (works for me, but hacky code so far).

Would you accept a pull request adding HTTP-01 support, or should I create a separate provider for that?

**Comment by vancluever** [comment]
Hey @saitho, yeah, sorry, this provider did support HTTP-01 at one point in time, but it was dropped eventually due the awkward circumstances surrounding using HTTP-01 with Terraform (usually, people are not running TF on the server being managed). As such it was hard to test and maintain.

If that's something that you need I'd definitely recommend looking into writing your own provider. You could also possibly use the [null](https://www.terraform.io/docs/providers/null/index.html) and [external](https://www.terraform.io/docs/providers/external/data_source.html) providers to put something together using external ACME management tools.

Good luck!
