### ISSUE TITLE
ACME renewal querying wrong NS

### ISSUE THREAD

**Issue by mengesb** [terraform-providers/terraform-provider-acme#11]
I have a private and public Route53 Zone of the same domain, and during renewal it adds the challenge to the public zone, but to verify, it's asking the private zone... therefore Route53 returns REFUSED.

```
acme_certificate.acme_wildcard: Modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/...)
...
acme_certificate.acme_wildcard: Still modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/..., 1m50s elapsed)
acme_certificate.acme_wildcard: Still modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/..., 2m0s elapsed)
acme_certificate.acme_wildcard: Still modifying... (ID: https://acme-v02.api.letsencrypt.org/ac...t/..., 2m10s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* acme_certificate.acme_wildcard: 1 error(s) occurred:

* acme_certificate.acme_wildcard: acme: Error -> One or more domains had a problem:
[host.domain.tld] Time limit exceeded. Last error: NS ns-512.awsdns-00.net. returned REFUSED for _acme-challenge.domain.tld.
```

I looked into my zones and noticed that `ns-512.awsdns-00.net` is only on my private zone, not on the public zone. Is there a way to control this?

**Comment by mengesb** [comment]
I also tried supplying the `config {}` map to the challenge segment, it is still querying the wrong NS server.

I think that it's not asking the right NS still. The source of where this runs knows that this zone is private, however it should be configured to query the NS of the zone that it's manipulating

**Comment by Joseph-Irving** [comment]
We just hit this exact issue, I can't see any obvious way to work around it, luckily the service that was effected by this wasn't that important, but if we want to continue using private zones and letsencrypt a solution would to this would be nice.

**Comment by mengesb** [comment]
I'm now hitting this problem on a new issue; despite using the config map options:

```
  dns_challenge {
    provider = "route53"

    config {
      AWS_HOSTED_ZONE_ID = "${local.zone_id}"
    }
  }
```

I see it attempting to verify against the SOA dns return of the Private zone, despite this plan not having anything to do with the private zone whatsoever

**Comment by vancluever** [comment]
#25 has been merged and this should be available next release!
