### ISSUE TITLE
AWS_PROFILE seems not working

### ISSUE THREAD

**Issue by xmackex** [terraform-providers/terraform-provider-acme#19]
Can't get `AWS_PROFILE` to work.
Tried access/secret keys, obviously they have worked.
Also tried to set AWS_PROFILE as env var, but it just doesn't work.
Also haven't found `AWS_PROFILE` in **lego** library. 

Terraform version:
```
Terraform v0.11.11
```

Acme version
```
+ provider.acme v1.0.1
```
---
DNS Challange
```hcl
  dns_challenge {
    provider = "route53"

    config {
      AWS_PROFILE = "mgmt"
      AWS_DEFAULT_REGION = "us-east-1"
    }
  }
```
---
`~/.aws/config`

```
[profile mgmt]
role_arn = arn:aws:iam::999999999999:role/mgmt
source_profile = main
```
---
Error
```
* acme_certificate.vault_dev: error creating certificate: acme: Error -> One or more domains had a problem:
[foo.sub.example.com] Error presenting token: failed to change Route 53 record set: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by xmackex** [comment]
My bad.
Adding ` AWS_SDK_LOAD_CONFIG = "true"` to the `config` fixed issue.
```
config {
  AWS_SDK_LOAD_CONFIG = "true"
  AWS_PROFILE = "mgmt"
  AWS_DEFAULT_REGION = "us-east-1"
}  
```

**Comment by vancluever** [comment]
Closing this through #20.

**Comment by SkUrRiEr** [comment]
The documentation describing these configuration options seems to have gone missing as I ran into this exact problem today.

**Comment by IronSavior** [comment]
Same here -- this is the only place I've seen mention of `AWS_SDK_LOAD_CONFIG`.

**Comment by JulianCBC** [comment]
The documentation for the provider is generated from https://github.com/go-acme/lego, so I've raised this issue there: https://github.com/go-acme/lego/issues/1061

**Comment by vancluever** [comment]
Thanks @JulianCBC. This is the correct answer and helps lessen maintenance burden over here!

**Comment by JulianCBC** [comment]
Ok, documentation update _should_ be in Lego v3.8: https://github.com/go-acme/lego/milestone/26?closed=1 so once that's released, it should flow through to this provider when it updates.
