### ISSUE TITLE
Resource to generate a PKCS #12 archive file

### ISSUE THREAD

**Issue by vancluever** [terraform-providers/terraform-provider-acme#2]
[Original issue](https://github.com/vancluever/terraform-provider-acme/issues/60) opened by @ebekker

Currently the ACME provider's resources are accessible as PEM outputs.  It would be useful to be able to produce a PKCS #12 (PKCS12 or alternatively PFX) archive format file out of these components, as there are cases where a PFX archive is preferred or even required.

I recommend supporting this resource in a more general-purpose manner, such that you can give it an optional private key PEM, and one or more certificates (i.e. an array of certificate PEM clobs). By doing so, the resource would be usable in tandem with other resources of this provider, as well as alternate providers, such as the out-of-the-box TLS provider.

Note, I have a similar request out in [terraform-provider-tls/#29](https://github.com/terraform-providers/terraform-provider-tls/issues/29) because I do feel it is more natural and general-purpose for that provider to implement this resource, however, I'm not sure how likely the are to produce it in a timely manner.

**Comment by vancluever** [comment]
@ebekkler just FYI that this resource _does_ support using an external certificate request, as seen [here](https://www.terraform.io/docs/providers/acme/r/certificate.html#using-an-external-csr). So it's possible to use the TLS provider if you want to create the CSR out-of-band. Since Terraform already provides this functionality (albeit in a different provider), it doesn't make sense to implement it here.

**Comment by ebekker** [comment]
@vancluever, glad to her the PKCS12 support is moving forward!

Although I'm not sure how the CSR comment is connected (maybe I misunderstand)?

Originally, when I posted this request, the ACME provider was implemented as a 3rd-party, external contribution to TF.  But now that's been brought into the fold as a first-class, fully supported provider by HashiCorp.  I was wondering what you thought about my comment about implementing the PKCS12 archive resource in the TLS provider?

**Comment by vancluever** [comment]
@ebekker might have mis-understood this, but I'm going off of this comment:

> I recommend supporting this resource in a more general-purpose manner, such that you can give it an optional private key PEM, and one or more certificates (i.e. an array of certificate PEM clobs). By doing so, the resource would be usable in tandem with other resources of this provider, as well as alternate providers, such as the out-of-the-box TLS provider.

I think you might have actually been referring to the generic PKCS12 resource that you've been talking about in the TLS provider, which if that's the case makes a lot more sense - I thought you were talking about the ability to provide external resources to the ACME provider, which we already support.

A more generic `tls_pfx_archive` resource or something similar in the TLS provider definitely makes sense to me, but would be a separate issue, of course. Its development would be separate from the ACME provider, though. I guess it would all depend on where exactly it would be needed - if you are generating the private key and CSR from the TLS provider, then it would be needed there for sure, but you aren't, #26 here should suffice.

**Comment by vancluever** [comment]
#26 has been merged and this should be available next release!
