### ISSUE TITLE
pass glcoud service account key by env rather than file 

### ISSUE THREAD

**Issue by vchrisb** [terraform-providers/terraform-provider-acme#22]
[lego v2.2](https://github.com/xenolf/lego/milestone/11) will allow specifying the gcloud service account key optional by setting `GCE_SERVICE_ACCOUNT` to the actual json https://github.com/xenolf/lego/pull/776, rather than `GCE_SERVICE_ACCOUNT_FILE` which requires a service account file.

Documentation will need to be updated, once v2.2 is leveraged for the terraform acme provider.

**Comment by vchrisb** [comment]
thank you

**Comment by vancluever** [comment]
@vchrisb no problem! Keep an eye out for it in the next release :+1:
