### ISSUE TITLE
timeout with gcloud dns provider

### ISSUE THREAD

**Issue by vchrisb** [terraform-providers/terraform-provider-acme#23]
I'm using the gcloud dns provider and do create a new subdomain zone in the same terraform run. I'm also creating NS records in the parent domain to forward request for the new subdomain to the newly created zone.
In the first terraform run the certificate creation does fail after 3 minutes but in the second run succeeds. 
I guess it just needs more than 3 minutes to finish dns propagation? Can I specify the timeout for the acme provider somewhere?

**Comment by Maniacal** [comment]
We ran into a similar issue. We aren't creating a new subzone in the call but we are creating the TXT record for the challenge and often timing out before propagation. Hopefully this will help.

The provider uses a library called 'lego' for interacting with DNS providers. The provider for gcloud has an environment variable you can set called "GCE_PROPAGATION_TIMEOUT" which defaults to 180 seconds https://github.com/xenolf/lego/blob/master/providers/dns/gcloud/googlecloud.go#L42

We were able to resolve our issue by setting that variable higher.

**Comment by vchrisb** [comment]
thank you, I'll try it!
