### ISSUE TITLE
Base64 encode p12 cert is missing padding

### ISSUE THREAD

**Issue by JimPaine** [terraform-providers/terraform-provider-acme#33]
When trying to use the base64 encoded string in Azure it fails due to the base64 string missing its padding.

After doing some digging it looks like the Encode method being used [here](https://github.com/terraform-providers/terraform-provider-acme/blob/master/acme/acme_structure.go#L443) is specifically stripping the padding out.

It also looks like it may be a simple fix to change as documented [here](https://golang.org/pkg/encoding/base64/#pkg-variables) The RawStdEncoding excludes the padding and the method StdEncoding keeps it.

I am happy to make the change and raise a PR but am aware this provider will be used across providers, who may or may not behave differently to Azure. It may be worth including both with and without padding or even removing it completely and letting the consuming generate it as required.

Happy to discuss then pick up the relevant work.

**Comment by vancluever** [comment]
@JimPaine if you want to make the PR I'd be happy to review.

I don't think we need separate fields, AFAIK Azure (and Microsoft, historically) is the only vendor that uses P12 cert formats, everyone else uses PEM. So I'd rather just have the one field and optimize it for Azure.

**Comment by JimPaine** [comment]
@vancluever will do, just need to setup an AWS environment to run the tests :) and I will raise the PR later this evening

**Comment by vancluever** [comment]
Hey all, this has now been merged and should be going out for release early next week. Thanks @JimPaine for the PR!
