### ISSUE TITLE
EOF error on version 1.3.0

### ISSUE THREAD

**Issue by jodersky** [terraform-providers/terraform-provider-acme#52]
The latest release of the terraform acme provider fails with the following error:

```
Error: Error running plan: 1 error(s) occurred:

* acme_certificate.tls: 1 error(s) occurred:

* acme_certificate.tls: unexpected EOF
```

where the relevant resource is defined as follows:
```
resource "acme_certificate" "tls" {
  account_key_pem           = "${acme_registration.tls.account_key_pem}"
  common_name               = "${element(var.domains, 0)}"
  subject_alternative_names = ["${slice(var.domains, 1, length(var.domains))}"]

  dns_challenge {
    provider = "gcloud"

    config {
      GCE_PROJECT = "${var.project}"
    }
  }
}
```

Note that this is a regression, as the above error does not happen on versions 1.1.x and 1.2.x. It only occurs on 1.3.0.

**Comment by vancluever** [comment]
@jodersky sorry, but I cannot reproduce this with the gcloud provider. `unexpected EOF` would indicate to me some sort of network connectivity issue. You may need to check some things related to that.

My config is (with TF 0.12):

```
resource "acme_certificate" "certificate" {
  account_key_pem           = "${acme_registration.reg.account_key_pem}"
  common_name               = "${element(var.domains, 0)}"
  subject_alternative_names = "${slice(var.domains, 1, length(var.domains))}"

  dns_challenge {
    provider = "gcloud"

    config = {
      GCE_PROJECT              = "<project name>"
      GCE_SERVICE_ACCOUNT_FILE = "<service account file>"
    }
  }
}
```

I've also tested this with Terraform 0.11.14.

If you'd like further assistance with this can you try again with TF_LOG=debug set as an environment variable and put the results in a gist:

```
TF_LOG=debug terraform apply
```

**Comment by jodersky** [comment]
Thanks for the pointer on TF_LOG.

>  You may need to check some things related to that.

I can confirm that this is in fact not an issue with the ACME provider. I'm not sure what's causing the issue, but testing this provider in isolation worked fine.
