### ISSUE TITLE
Terraform destroy

### ISSUE THREAD

**Issue by EricMCornelius** [terraform-providers/terraform-provider-acme#68]
Hi there,

I'm receiving the following error after attempting to destroy terraform infrastructure:
```Error: acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:unauthorized :: An account with the provided public key exists but is deactivated, url:```

I'm not well versed in Go or terraform provider implementation in general, so I'm afraid it might take me a while to be able to pitch in for a fix, but I'm curious if this is a known issue that should be handled.

Note, I'm using terraform 0.12.1 and terraform-provider-acme_v1.3.4_x4

**Comment by giorgiosironi** [comment]
I have seen this error after a `acme_registration` resource has been removed, as this results in the corresponding account being deactivated on Let's Encrypt.

Tainting the resource doesn't help, nor commenting it out. May have to manually remove it from the state...

**Comment by giorgiosironi** [comment]
From a quick look at the source code this doesn't look like something that is explicitly handled, but it's just a generic error coming from Let's Encrypt that makes the refresh operation fail.

**Comment by giorgiosironi** [comment]
Tried also `terraform state rm acme_registration.reg` (substitute your resource name). This makes `terraform refresh` successful again after commenting out all the related `acme_*` resources.

**Comment by giorgiosironi** [comment]
Essentially once the registration key is in this state (for whatever reason), resources cannot be modified anymore so the only way out seems to be:

- `terraform state rm` all the `acme_*` resources
- comment them out and apply
- uncomment them and apply to re-create them

Going with this plan.

**Comment by vancluever** [comment]
Hey @EricMCornelius and @giorgiosironi , thanks for the report. 

I have a repro and I'm working to fix it. This indeed happens when the account is deactivated and a refresh/plan is made afterwards. It'll be fixed so that it's just dropped if a refresh is attempted on a deactivated key.

Thanks!

**Comment by vancluever** [comment]
Should be fixed with the v1.4.0 release.

**Comment by tjhiggins** [comment]
@vancluever Hitting this issue on a created certificate when I remove it from the template. Not doing a destroy, but trying to re-apply after removing from the template. Only fix seems to be editing the remote state file and removing the acme_certificate. 

```
Error: acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:unauthorized :: An account with the provided public key exists but is deactivated, url: 
```

**Comment by Marvalero** [comment]
I am seeing the same thing, after applying a change, it destroys the registration but it does not create a new one
```
Error: acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:unauthorized :: An account with the provided public key exists but is deactivated, url: 

  on tls.tf line 25, in resource "acme_registration" "registration":
  25: resource "acme_registration" "registration" {
```

**Comment by jdstone-loansnap** [comment]
Yes, this still exists for me as well.

```
$ terraform --version
Terraform v0.11.14
+ provider.acme v1.4.0
```

**Comment by jdstone-loansnap** [comment]
Any update on this?

**Comment by abeluck** [comment]
Also ran into this today.

**Comment by hieumoscow** [comment]
Hi team, is there resolution to this issue?
It happened after destroy & recreate.

Error: acme: error: 403 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:unauthorized :: An account with the provided public key exists but is deactivated, url:

**Comment by zfogg** [comment]
+1

**Comment by sblausten** [comment]
+1

**Comment by zfogg** [comment]
hey i figured this out btw, for anyone googling! letsencrypt has a limit of *5 certificate issues per domain* on a *7 day rolling window*. you have exactly three options:
* wait for letsencrypt's rolling window to pass for your domain's certificate issue requests
* choose a different domain/subdomain to request a certificate for from letsencrypt
* use something other than letsencrypt to get a certificate issued
