### ISSUE TITLE
Certificate renewal not applied with terraform 0.12

### ISSUE THREAD

**Issue by gansb** [terraform-providers/terraform-provider-acme#73]
When a certificate is due for renewal, the provider detects this and outputs the correct plan (`resourceACMECertificateCustomizeDiff`). However, when the update is applied (`resourceACMECertificateUpdate`) the check `d.HasChange("certificate_pem")` returns false and no update is made, leading to the certificate not being renewed.

I guess it's related to https://github.com/hashicorp/terraform/issues/21977

**Comment by renchap** [comment]
+1, I have been hit by this as well. This is a critical issue as `terraform apply` does not display any error and the run is marked as success, but the certificate is not renewed.
