### ISSUE TITLE
Validations are slow

### ISSUE THREAD

**Issue by jbergknoff-rival** [terraform-providers/terraform-provider-acme#81]
Hi, sorry for the vague title. First off, thanks for this great provider!

I'm using this to register a certificate with Let's Encrypt, using Route53 for the DNS challenge. The certificate has something like 20 SANs. It seems that each validation happens in sequence, and each takes 30-60 seconds.

Also, after all the SANs are validated successfully (or fail to validate), the DNS records are removed in sequence, which takes another 30-60 seconds.

All in all, it takes a little over half an hour for my certificate to be validated.

Am I correct in understanding that these validations are all happening in sequence (there's no debug output, so I'm speculating based on when records appear in Route53)? Would it cause problems if they were attempted in parallel? Thanks.

**Comment by vancluever** [comment]
@jbergknoff-rival unfortunately this is something that is a part of the lego implementation and not something we have too much control over.

https://github.com/go-acme/lego/pull/607 indicates that _some_ degree of "parallelism" is done to ensure that all records are submitted before the propagation checks, but it's not truly parallel.

You might want to ask more about this in the lego project.

Thanks!

**Comment by jbergknoff-rival** [comment]
Thanks for pointing me in the right direction. I wasn't quite sure where the boundaries were between this provider and lego.
