### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by nfagerlund** [terraform-providers/terraform-provider-acme#86]
Commit 54e49adc607 added some broken links, which are breaking builds for terraform.io. 

The broken links are in:

- docs/dns_providers/exec.html.markdown (linking to `/dns/exec`)
- docs/dns_providers/httpreq.html.markdown (linking to `/dns/httpreq`)

Where were these supposed to point to?

**Comment by vancluever** [comment]
@nfagerlund thanks for the heads up! Can you look at 033c077f2f209a9266dca471382bc262acfd0fdf and tell me if that will fix it? If so I'll throw this on stable-website so it can be deployed.

**Comment by nfagerlund** [comment]
@vancluever That'll fix the build, but it leaves another issue — namely, what's the point of these links, anyway? Now that they just jump you to the top of the same page, it seems like they're just there to troll me??? 😂 

Could you remove them instead, if they weren't intended to actually go anywhere? And while you're at it, there's grammar and capitalization errors:

Now:

> ...perform DNS challenges for the `acme_certificate` resource with External program.

Looks like it should be:

> ...perform DNS challenges for the `acme_certificate` resource with an external program.

**Comment by vancluever** [comment]
@nfagerlund it's auto-generated, so I'd prefer to keep the exceptions down. The vast majority of the DNS provider docs work with the existing template both with it comes to hyperlinks and grammatical correctness, these are just the odd ones out.

**Comment by nfagerlund** [comment]
@vancluever Oh!!! Ok, that explains everything. 😅 Well, in that case, yeah, that commit should be good enough. 👍🏼

**Comment by vancluever** [comment]
I was playing with the templates after writing that 😛 so there might be something here that we can do! 

In the meantime, I've just pushed the commit with the fix to stable-website.

**Comment by vancluever** [comment]
Alright, closing this now. 843e936c21356902dd53b48283e5f2fbf7e83d57 has some additional changes so that the only real edge left is the odd capitalization on providers that are not proper nouns. Everything else should be cleaned up! This has been picked to stable-website and should show up on the next build.
