### ISSUE TITLE
The argument "server_url" is required, but was not set.

### ISSUE THREAD

**Issue by rolljee** [terraform-providers/terraform-provider-acme#96]
Hi there 👋 

I have an issue with acme provider i cannot resolve myself

I am deploying a rather big cluster an AKS and getting ssl with acme provider.

All is working fine for the plan / apply part, my issue is concerning the terraform destroy command.

When i run `terraform destroy` on my cluster i always have this `The argument "server_url" is required, but was not set.` and the destroy process is cut off

```bash
provider "acme" {
  version    = "~> 1.5"
  server_url = "https://acme-v02.api.letsencrypt.org/directory"
}
```
I am using gandiv5 dns challange and using the tls provider to get my key/certificate request
Any one have already ran into this issue ?

**Comment by jrauschenbusch** [comment]
Same here. Removal of all acme resources incl. the provider leads to the above mentioned error.

**Comment by rolljee** [comment]
@jrauschenbusch I found out my problem wasn't because of acme provider, but instead in my terraform destroy command I simply wasn't pointing to the state. I will close this issue since my problems is now resolved, i honestly forgot i has opened this a while back ago 😁
